src/docs/00-get-started/01-server-installation.md
I noticed that the names used are not consistent when I was going through the docs.
=> (fix) domain name in domain register command

src/.vuepress/config.js, src/docs/04-java-client/18-workflow-replay-shadowing.md
Add doc for Java client shadowing
=> Add doc for Java client shadowing

src/docs/01-get-started/02-java-hello-world.md
Hi there,
just proposing an small fix. The Workflow interface must be public for making it work. I copied code from here, and I wasted some time figuring it out.
=> Add missing public access modifier

src/docs/03-concepts/07-archival.md
- Remove outdate descriptions about visibility archival
- Add samples for enabling and using visibility archival
- Add some FAQ questions
=> Update Archival document

src/docs/03-concepts/01-workflows.md
=> fix workflow method typo

src/blog/_posts/2022-01-31-community-spotlight-january-2022.md
=> Add January 2022 Community Spotlight Update to Cadence blog

src/blog/_posts/2022-01-31-community-spotlight-january-2022.md, src/blog/_posts/2022-02-28-community-spotlight-february-2022.md
Added new blog post for Cadence Community Spotlight Update for February 2022
=> Blog post for February Community Spotlight update

src/blog/_posts/2022-02-28-community-spotlight-february-2022.md
Minor fix for display for of title for February Community Spotlight blog post regarding Technical Office Hours session.
=> Fix title display for Tech Office Hours

LICENSE, README.md
Added a LICENSE file with the MIT Licence and updated README to reference it.
=> Added MIT License and updated README to link to it

src/blog/_posts/2022-03-31 community-spotlight-update-march-2022.md
Create monthly blog entry for March 2022 Community Spotlight Update
=> Add Blog Entry for March Community Spotlight Update

src/blog/_posts/2022-04-30-community-spotlight-update-april-2022.md
Monthly blog post for Community Spotlight update - April 2022
=> Blog Post for April Community Spotlight Update

src/blog/_posts/2022-05-31-community-spotlight-update-may-2022.md
Add a new blog entry for community spotlight update May 2022
=> Add Community Spotlight Update May 2022

src/blog/_posts/2022-05-31-community-spotlight-update-may-2022.md, src/blog/_posts/2022-06-30-community-spotlight-update-june-2022.md
Create Community Spotlight Update for Cadence Blog - June 2022
=> Add Community Spotlight Update to blog for June 2022

src/docs/01-get-started/01-server-installation.md
Updated the prometheus config file link as the earlier one leads to a 404 page.
=> Corrected the prometheus yaml file link

src/blog/_posts/2023-01-31-community-spotlight-january-2023.md
Create blog post for Community Spotlight Update - January 2023
=> Create blog post for January 2023 Community Spotlight Update

.github/workflows/publish-to-gh-pages.yml
Publishing equivalent to #138 , as that part of the `master`-branch build process is now working.
=> Update publish-to-gh-pages like build CI

src/blog/_posts/2023-03-31-community-spotlight-march-2023.md
Tidy up Webinar description link
=> Correct error in Webinar description link in March Community Blog Update

src/blog/_posts/2023-07-31-community-spotlight-july-2023.md
Adding community update blog post for July 2023
=> Community Spotlight Blog Update for July 2023

README.md
It is not obvious how to add new pages, especially that you need to add them to the config file in a hidden folder.
=> Updated readme with instructions on how to add new pages to docs

src/.vuepress/config.js, src/docs/05-go-client/02.5-starting-workflows.md
Added docs on how to start workflows from the go client
This includes docs on how to add jitter to the workflows.
=> Added docs on how to start workflows from the go client

src/.vuepress/config.js, src/docs/03-concepts/10-http-api.md, src/docs/03-concepts/index.md
Add documentation for some HTTP API endpoints introduced in https://github.com/uber/cadence/pull/5338 and https://github.com/uber/cadence/pull/5305.
=> Add HTTP API documentation

src/blog/_posts/2023-11-30-community-spotlight-update-november-2023.md
Create Community Spotlight Blog Update for November 2023
=> Create Community Spotlight Blog Update for November 2023

src/docs/07-operation-guide/05-migration.md
=> Update migration doc

src/docs/04-java-client/index.md
update cadence-java-client with release information
- using gradle implements
- add latest version badge
=> update cadence-java-client with release information

src/docs/07-operation-guide/01-setup.md
Adding more details on how `yaml` configuration is loaded and how ENV variables can be used
=> Add more details on server configuration options

src/blog/_posts/2024-09-05-workflow-specific-rate-limits.md
Post on workflow ID rate limits
=> Added post on workflow id ratelimits

src/.vuepress/config.js, src/blog/.vuepress/config.js
This adds the latest version of google analytics script onto the site and blog.
Access to analytics will be granted to Cadence maintainers.
=> Adding GA tracking code on site and blog

src/.vuepress/config.js, src/docs/08-workflow-troubleshooting/02-activity-failures.md
Adding a page on activity failures and errors to the workflow troubleshooting section
Tested the changes locally
=> [Wf-Diagnostics] add troubleshooting guide for activity failures in a workflow

src/docs/08-workflow-troubleshooting/02-activity-failures.md
Adding a section on blob size limits to the workflow troubleshooting section. 
Tested the changes locally
=> [Wf-Diagnostics] update troubleshooting guide for blob size limits

docs/01-get-started/02-java-hello-world.md, docs/03-concepts/05-topology.md, docs/05-go-client/01-workers.md, docs/05-go-client/05-child-workflows.md, docs/06-cli/index.md
Cherry picking contributor changes from branches which went stale as well as other minor updates.
=> Contributor changes

docs/06-cli/index.md
to push adoption for grpc over tchannel
=> Update cadence docs to use grpc and fix domain name

docs/02-use-cases/06-batch-job.md
I was getting a few common questions about batch operations, so I figured I should just update our docs to include better information about them. Not 100% sure this is the right place to put this level of granularity, happy to move it out if it's not
=> adds basic example for batch operations

docs/02-use-cases/06-batch-job.md
I goofed up a few parts of the earlier merge, fixing and applying some readability suggestions by @Groxx
=> fix some bad merging in the batch examples

blog/2025-07-01-safe-deployment-of-versioned-workflows/2025-07-01-safe-deployment-of-versioned-workflows.md
Removing the dynamic configuration until we provide an opinionated API for dynamic versioning solution.
=> Removing dynamic configuration from the post to reevaluate and provide a better solution

docs/05-go-client/21-sleep.md, sidebars.ts
**Whats new**
Adding workflow.sleep documentation
**Testing**
Locally
=> Documentation for Workflow.sleep

blog/2025-08-06-workflow-diagnostics.md, blog/authors.yml
This feature was ready earlier this year but now the UI integration is also complete and soon to be launched
=> [Wf-Diagnostics] add a post on workflow diagnostics

docs/01-get-started/03-golang-hello-world.md
Hey maintainers!
Your [Golang tutorial](https://cadenceworkflow.io/docs/get-started/golang-hello-world) has been out-dated.
I am submitting this pull request to update it. Please review!
- Step 1. Implement A Cadence Worker Service
- Add step to initialize the Go module.
- Update incorrect imported module `apiv1 "github.com/uber/cadence-idl/go/proto/api/v1"` instead of `apiv1 "github.com/cadence-workflow/cadence-idl/go/proto/api/v1"`.
- Use `worker.NewV2` to initialize the worker since `worker.New` is deprecated.
- Add step to install the dependencies.
- Step 2. Write a simple Cadence hello world activity and workflow
- Add the missing modules that need to be imported (if they were not automatically added).
- Step 3. Run the workflow with Cadence CLI
- Add the alternative shell command.
=> Update Golang HelloWorld tutorial

docusaurus.config.ts
this header's stale, removing. 
It's possible this will mess up since I'm not super familiar with this, if it does I'll revert.
=> remove header
