cadence-workflow/Cadence-Docs

- .github/workflows/publish-to-gh-pages.yml
- package.json
- src/.vuepress/config.js
Add an optional secret `CUSTOM_DOMAIN` which allows a user to set the domain for where to deploy cadence docs. If secret is not set it will create an empty file which does nothing.
The idea of setting this information in a secret is so that if the project is forked, users don't accidentally publish CNAME. 
However it does allow a user to publish their fork to their own domain if they want to.
Removed old way of publishing CNAME.
> Configure custom domain for cadence docs

- src/.vuepress/config.js
Created a link under github dropdown to navigate to github cadence docs page.
> Link to cadence docs in navigation bar

- src/index.md
- Fixing get started link on homepage. Now redirects to Get started section.
- Updating date in footer to 2021.
> Fix broken link on homepage

- src/docs/00-get-started/01-server-installation.md
docker run --network=host --rm ubercadence/cli:master --do test-domain domain register -rd 1
docker run --network=host --rm ubercadence/cli:master --do sample-domain domain describe
Example names are inconsistent
> Fix wrong name

- src/docs/01-get-started/01-server-installation.md
It appears that `prometheus_config.yml` is required now (I believe https://github.com/uber/cadence/commit/a86abb4825db23200c593c5f2637e256f2d083ab to be the culprit of this requirement).
> Add missing Prometheus config

- src/docs/03-concepts/09-search-workflows.md
For better clearness.
`Filtering` is not a useful word. I haven't seen ppl use `filtering` to describe this feature. However, most of other places is using `advanced visibility`.
> Rename title for advanced visibility

- src/docs/04-java-client/03-implementing-workflows.md
Section below actually talks about workflows, not activities. Fixing header to reflect that. This confused a user.
> Fix section header that talks about workflows

- src/docs/05-go-client/index.md
Create workflows link on [go-client intro page](https://cadenceworkflow.io/docs/go-client/#overview) is broken. It links to the page https://cadenceworkflow.io/docs/05-go-client/create-workflows/ which is incorrect and does not exist.
> Fix create workflows link on go-client intro page

- src/docs/01-get-started/02-java-hello-world.md
- src/docs/01-get-started/03-golang-hello-world.md
I spent some time working on the example here before working out that the sample repo was a much easier place to get started. Suggest this update to send users more directly to the sample repo if they just want to build and run something.
> Make samples more prominent in getting started section

- src/docs/07-operation-guide/01-setup.md
Noticed what I'm pretty sure is a typo - Elasticache(redis/memcache) should be Elasticsearch/OpenSearch
> Fix Elasticache typo

- src/docs/03-concepts/01-workflows.md
This commit fixes typos in the document.
Reference to non-existing function `chargeMonthlyFee` is replaced with `chargeCustomerForBillingPeriod`
> Fix typos in 01-workflows.md

- src/docs/03-concepts/05-topology.md
- new main architecture diagram as discussed on Slack
- removed the abbreviation of the service names from the text as they were no longer used anywhere
- the Cadence Overview diagram didn't appear in preview so I uploaded the same diagram again to be safe
- the links on the page like _:decision_task:decision_tasks:_ aren't working in preview but I haven't touched them so I'm assuming that's just a limitation of preview mode?
> Updated main architecture diagram

- src/blog/_posts/2022-03-31 community-spotlight-update-march-2022.md
Minor fix to add link to Understanding Cadence for Ops and SREs whitepaper in the Cadence in the News section of March Community Spotlight
> Add link to Understanding Cadence for Ops and SREs whitepaper

- src/docs/02-use-cases/03-polling.md
Updated Polling Use Cases to include a link to a Cadence Polling Cookbook  that includes a detailed example for polling external services
> Added Example for Polling External Services in Cadence Polling use cases section

- src/docs/04-java-client/04-starting-workflow-executions.md
- src/docs/05-go-client/01-workers.md
Currently, the Java and Go Client SDKs do not offer initialisation examples for creating TLS-enabled clients.
We've added an example for each in the appropriate pages, as well as a plain (non-TLS) gRPC example for the Go SDK. 
We've also made some basic edits done some formatting on the surrounding text just to integrate the examples in the documentation flow.
> Add gRPC with TLS examples for Java and Go Clients

- src/docs/04-java-client/08-distributed-cron.md
- src/docs/05-go-client/16-distributed-cron.md
Updating with a more advanced example showing that cadence cron workflows also support "/" and "-" operators in cron scheduling.
> Adding more advanced example of the scheduling cadence clients support.

- .github/workflows/build.yml
This is probably worth upgrading, but at the very least this makes our CI use the same (major) version as `package.json`, `.node-version`, etc dictate is our supported version.
Upgrading to v18 in the future should be easy, just change the version in this file.  If we want to support both, we can do the strategy-matrix thing that the node template shows.  But since it's a static generator I don't really think that's all that necessary.
> Pin CI builds to node v16

- README.md
When a github action workflow is disabled it disables the badge in the README.md.
I changed the source image of the badges to use shield.io 
Disabled gh workflow which triggered this issue:
https://github.com/uber/Cadence-Docs/actions/workflows/nightly-integration-test.yml
Example of issue:
> fix: badges in readme

- src/docs/03-concepts/07-archival.md
I believe we made this bucket while we were testing Archival feature.
It is not owned by Uber anymore, and it also may be misleading to have
the same mentioned.
> Changing name of s3 bucket since dev-cad' possession is released

- src/docs/01-get-started/01-server-installation.md
- src/docs/01-get-started/03-golang-hello-world.md
1. Typo fixes
2. Fixes to code
- Added package line
- Changed the host port number
- Added error handling to `http.ListenAndServe`
- Added import to `context`
3. Fix to cli `workflow start` command
- Removed `--env` as it's not part of the latest Cadence CLI attribute list
> Fixes to get started docs

- src/.vuepress/config.js
overview page is redirected by default but would be good to also have in sidebar
> [Wf-Diagnostics] add link to troubleshooting overview page in sidebar

- src/.vuepress/config.js
- src/docs/08-workflow-troubleshooting/01-timeouts.md
- src/docs/08-workflow-troubleshooting/03-retries.md
Adding a page on activity retries and workflow retries to the workflow troubleshooting section. also updated the page on timeouts to include retry policy suggestions
Tested the changes locally
> [Wf-Diagnostics] add troubleshooting guide for activity and workflow retries

- .github/workflows/publish-to-gh-pages.yml
Checked environment variables at the build step on the deployment GH action.
Run: https://github.com/cadence-workflow/Cadence-Docs/actions/runs/12602826174/job/35126630404
It's correct, CADENCE_DOCS_URL is redacted automatically since it's stored as a secret.
```
CADENCE_DOCS_URL is https://***
PROJECT_NAME is Cadence-Docs
BASE_URL is /
ORGANIZATION_NAME is cadence-workflow
```
In case something goes wrong, it can be deployed from a local environment:
```
export CADENCE_DOCS_URL=https://cadenceworkflow.io
export BASE_URL=/
export ORGANIZATION_NAME=cadence-workflow
export PROJECT_NAME=Cadence-Docs
touch static/CNAME
echo "cadenceworkflow.io" > static/CNAME
npm run deploy
```
> Enable deployments

- sidebars.ts
This is just missing from the new version of the docs, the page already exists.
> Add concepts/workflows to sidebar

- .github/workflows/publish-to-gh-pages.yml
This copies repo history in order to show author attribution based on commit history.
https://github.com/actions/checkout?tab=readme-ov-file#fetch-all-history-for-all-tags-and-branches
> Fix author attribution based on git history

- docusaurus.config.ts
- src/css/fonts.css
When loading the documentation, there are some flashes of unstyled text due to the fonts not being ready at the time.
Added preloading for the main fonts used as well as changed the font-display to fallback in case they do not load.
Logo could take brief time to load as well on a very slow connection, added properties to prevent text sliding on load
https://css-tricks.com/fout-foit-foft/
> Fix flash of unstyled text

- docs/03-concepts/08-cross-dc-replication.md
- docs/06-cli/index.md
- docs/07-operation-guide/05-migration.md
Updating the cluster configu documentation to match the new syntax, see PR: https://github.com/cadence-workflow/cadence/pull/6658 for context
> Updated the cluster command to the new syntax with a ,

- docs/03-concepts/05-topology.md
The link to gRPC API was broken, leading to 404 error.
> Fix gRPC API link

- .github/workflows/fetch-release-data.yml
This updates the Github action to create a PR for data updates instead of creating commits directly to master branch.
We can't commit directly to master branch due to branch protection rules.
The upside is that all data updates will be reviewed before deployment. 
Example of PR:
PR and branch can be deleted and the github action will recreate it if needed using the default branch as the base, this is useful in case history diverges or there is stale data on the branch.
> Auto PRs for release updates

- docs/06-cli/index.md
Correct domain name `samples-domain` in the registering domain command
> Fix typo in cli/index.md

- docs/04-java-client/01-client-overview.md
- docs/04-java-client/index.md
- docusaurus.config.ts
Adding feature matrix between cadence-go-client and cadence-java-client
Screenshot (updated March 12th)
Improved links to Java resources
Enabled `showLastUpdateAuthor` and `showLastUpdateTime` for documentation pages
> Improve Java client documentation

- docs/01-get-started/01-server-installation.md
**What changed?**
Fix for Incorrect curl command to download compose files
**Why?**
https://github.com/cadence-workflow/Cadence-Docs/issues/230
Hi, So in reference to this https://github.com/cadence-workflow/Cadence-Docs/issues/171. I think it still persists. So running the curl command mentioned in the docs
curl -O https://raw.githubusercontent.com/cadence-workflow/cadence/master/docker/docker-compose.yml && curl -O https://raw.githubusercontent.com/cadence-workflow/cadence/master/docker/prometheus/prometheus.yml
This only downloads docker-compose.yml and promethues.yml
.
├── docker-compose.yml
└── prometheus.yml
But inside docker-compose.yml it clearly has these volumes under promethues and grafana service. Prometheus looks for prometheus.yml inside promethues directory and Grafana …
> Fix for Incorrect curl command to download compose files

- sidebars.ts
This page already exists, it was missed during the migration
> Add Java implementing-activities to sidebar

- docs/06-cli/index.md
The cli command confusingly has both the `restart` command and the `reset` command which sound similar and do very similar things but are internally very different. So disambiguating them here in the docs. 
The `restart` command (which is conceptually a command to start the workflow again with identical arguments from the beginning) is probably not worth mentioning upfront as its functionality is nearly entirely superceded by the more complicated/useful/powerful reset command.
> Minor documentation update

- docs/00-codelabs/01-workflow-tests-go-replayer-shadower.md
- sidebars.ts
Added:
- Sidebar for Codelab, inserted between Concepts & Java Client (sidebars.ts)
- Created new document to be the first Codelab (00-codelabs/01-workflow-tests-go-replayer-shadower.md)
Caveat: 
- The order of the sidebar tabs seem to be controlled declaratively by sidebars.ts. I don't know why all the folders in the docs directory are numbered. But it doesn't seem to matter when running locally. I therefore didn't want renumber folder 04-* onward just to insert the Codelabs sidebar tab. If my assumptions are incorrect, let me know.
> Add First Codelab Tutorial

- docs/05-go-client/21-worker-auto-scaling.md
**Issue:**
Want the most compelling dashboards at the top to grab attention. Give the reader a compelling reason to continue reading. 
**Solution:**
- Created attention grabbing headline
- Moved CPU and Worker instance dashboards to the top after the headline
- Created a link to the dashboards in the old location
> Created an attention grabbing headline at the top

- docs/01-get-started/03-golang-hello-world.md
**What changed?**
- Update Golang Hello World tutorial: register workflow and activity using worker instance due to the deprecated global functions.
- Convert 4-spaces indentation to tab because of Go coding styles.
**Why?**
Update Golang Hello World tutorial.
**How did you test it?**
local tests
> docs: update Golang Hello World tutorial

- docs/05-go-client/21-worker-auto-scaling.md
Add embedded demo video  to top of new golang worker autoscaling documentation
> Add youtube video to top of worker auto scaling

- NOTICE
**What changed?**
Added proper attribution for these packages along with links to their respective Creative Commons licenses.
> Add attribution for caniuse-lite and mdn-data in NOTICE file

- docs/03-concepts/09-search-workflows.md
Add a space between the title and opening brackets for the Search Workflows page.
Ran locally.
> Fix spacing in Search Workflows title
